version: '3.7'

services:
  mongodb:
    container_name: mongodb-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 21017:21017

  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/studies/ts-tdd-ddd-clean_architecture-solid
    command: bash -c "npm install --omit=dev && npm run debug"
    restart: always
    volumes:
      - ./dist/:/usr/src/studies/ts-tdd-ddd-clean_architecture-solid/dist/
      - ./package.json:/usr/src/studies/ts-tdd-ddd-clean_architecture-solid/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongodb
    environment:
      PORT: 5050
      JWT_SECRET: 'AXQ17*!#634R1S'
      MONGO_CONNECT_URL: 'mongodb://mongodb:27017/test'
